version = 0.1
[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "website-back-end"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-12hh2jvassl7v"
s3_prefix = "website-back-end"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
