AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  website-back-end

  Sample SAM Template for website-back-end

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  visitorCounterApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: visitorCounterApi
      StageName: prod
      Cors:
        AllowMethods: "'OPTIONS,POST,GET,PUT,DELETE'"
        AllowHeaders: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token,Z-Client-Timezone'"
        AllowOrigin: "'*'"
        MaxAge: "'3600'"
      GatewayResponses:
        DEFAULT_4xx:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Methods: "'OPTIONS,POST,GET,PUT,DELETE'"
              Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
              Access-Control-Allow-Origin: "'*'"


  visitorCounterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: visitorCounterFunction #this works
      CodeUri: prod/
      Handler: app.lambda_handler
      Runtime: python3.8
      Policies:
      - AmazonDynamoDBFullAccess
      - AWSLambdaBasicExecutionRole
      Events:
        visitorCounter:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /{proxy+}
            Method: GET
            RestApiId: !Ref visitorCounterApi

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  visitorCounterApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${visitorCounterApi}.execute-api.${AWS::Region}.amazonaws.com/prod/counter/GET/"  #this didnt affect it?
  visitorCounterFunction: #not sure if this works
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt visitorCounterFunction.Arn
  visitorCounterFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt visitorCounterFunctionRole.Arn
