image: python:latest

stages:
  - deploy

production:
  stage: deploy
  before_script:
    - pip3 install awscli --upgrade
    - pip3 install aws-sam-cli --upgrade
  script:
    - sam build
    - sam package --output-template-file packaged.yaml --s3-bucket <johnrteixeira.com-backend>
    - sam deploy --template-file packaged.yaml --stack-name gitlabpoc --s3-bucket <johnrteixeira.com-backend> --capabilities CAPA
  environment: production